# Equipo 3 - Perspectiva Estelar

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("hwc.csv", usecols=["P_NAME", "P_HABITABLE", "S_TYPE", "S_TYPE_TEMP", "S_TEMPERATURE", "S_MASS", "S_RADIUS", "S_LOG_LUM",
"S_LOG_G", "S_AGE", "S_METALLICITY", "S_DISTANCE", "S_HZ_OPT_MIN", "S_HZ_OPT_MAX", "S_HZ_CON_MIN",
"S_HZ_CON_MAX", "S_TIDAL_LOCK", "S_SNOW_LINE", "S_ABIO_ZONE", "P_ESI"])
data

,P_NAME,S_TYPE,S_DISTANCE,S_TEMPERATURE,S_MASS,S_RADIUS,S_METALLICITY,S_AGE,S_LOG_LUM,S_LOG_G,S_TYPE_TEMP,S_HZ_OPT_MIN,S_HZ_OPT_MAX,S_HZ_CON_MIN,S_HZ_CON_MAX,S_SNOW_LINE,S_ABIO_ZONE,S_TIDAL_LOCK,P_HABITABLE,P_ESI
0,OGLE-2016-BLG-1227L b,NaN,NaN,NaN,0.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.214133,0,NaN
1,Kepler-276 c,NaN,1144.8600,5779.0,1.10,1.03,0.02,0.40,-0.089,4.46,G,0.677337,1.595742,0.857931,1.512908,2.437046,2.097783,0.316980,0,0.272032
2,Kepler-829 b,NaN,1073.7600,5698.0,0.98,0.97,0.03,4.68,0.040,4.46,G,0.789603,1.864342,1.000132,1.767566,2.827247,1.756317,0.459559,0,0.254763
3,K2-283 b,NaN,402.9150,5060.0,0.89,0.82,0.28,NaN,-0.524,4.56,K,0.427216,1.030473,0.541131,0.976981,1.476943,0.568374,0.443760,0,0.193906
4,Kepler-477 b,NaN,367.0000,5240.0,0.87,0.79,-0.04,2.09,-0.372,4.58,K,0.504264,1.208168,0.638721,1.145452,1.759397,0.768502,0.386150,0,0.276721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5594,HD 222155 b,G2 V,50.6078,5701.0,1.21,1.85,-0.18,8.20,0.509,3.99,G,1.354663,3.198245,1.715852,3.032227,4.851363,1.893917,0.541322,0,0.178593
5595,HD 88986 b,G2 V,33.2673,5861.0,1.25,1.54,0.06,7.90,0.393,4.16,G,1.173962,2.759889,1.486965,2.616626,4.244864,2.520276,0.543834,0,0.379540
5596,Kepler-30 b,NaN,914.2210,5498.0,0.99,0.95,0.18,2.00,-0.237,4.77,G,0.580739,1.379360,0.735584,1.307759,2.055246,1.249824,0.400198,0,0.241771
5597,HD 3167 d,K0 V,47.2899,5261.0,0.84,0.88,0.04,7.80,-0.270,4.47,K,0.566466,1.356182,0.717509,1.285783,1.978626,0.787469,0.475336,0,0.272975
5598,OGLE-2019-BLG-1180L b,NaN,6070.0000,NaN,0.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.377983,0,NaN

In [13]:
data.sort_values("P_ESI",ascending=False)

,P_NAME,P_DETECTION,P_DISCOVERY_FACILITY,P_YEAR,P_UPDATE,P_MASS,P_MASS_ERROR_MIN,P_MASS_ERROR_MAX,P_MASS_LIMIT,P_MASS_ORIGIN,...,S_ABIO_ZONE,S_TIDAL_LOCK,P_HABZONE_OPT,P_HABZONE_CON,P_TYPE_TEMP,P_HABITABLE,P_ESI,S_CONSTELLATION,S_CONSTELLATION_ABR,S_CONSTELLATION_ENG
934,Teegarden's Star b,Radial Velocity,Calar Alto Observatory,2019,2024-03-05,1.16000,-0.11000,0.12000,0,Msini,...,0.008444,0.234823,1,0,Warm,1,0.968362,Aries,Ari,Ram
537,TOI-700 d,Transit,Transiting Exoplanet Survey Satellite (TESS),2020,2024-02-16,1.25000,NaN,NaN,0,M-R relationship,...,0.028274,0.286631,1,1,Warm,1,0.941176,Dorado,Dor,Goldfish
1291,Kepler-1649 c,Transit,Kepler,2020,2020-04-16,1.20000,NaN,NaN,0,M-R relationship,...,0.015156,0.269791,1,0,Warm,1,0.925298,Cygnus,Cyg,Swan
480,TOI-700 e,Transit,Transiting Exoplanet Survey Satellite (TESS),2023,2024-02-16,0.81800,NaN,NaN,0,M-R relationship,...,0.028274,0.286631,1,0,Warm,1,0.912032,Dorado,Dor,Goldfish
2239,TRAPPIST-1 d,Transit,La Silla Observatory,2016,2022-11-14,0.38800,-0.01200,0.01200,0,Mass,...,0.003648,0.142824,1,0,Warm,1,0.907662,Aquarius,Aqr,Water Carrier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5575,OGLE-2019-BLG-0249L b,Microlensing,OGLE,2023,2023-05-26,2262.93830,-467.20776,467.20776,0,Mass,...,NaN,0.447059,0,0,NaN,0,NaN,Scorpius,Sco,Scorpion
5576,OGLE-2019-BLG-0679L b,Microlensing,OGLE,2023,2023-05-26,1061.54690,-603.87397,603.87397,0,Mass,...,NaN,0.401667,0,0,NaN,0,NaN,Ophiuchus,Oph,Serpent Holder
5591,KMT-2019-BLG-1216L b,Microlensing,KMTNet,2023,2023-05-26,29.87587,-15.89142,15.89142,0,Mass,...,NaN,0.337059,0,0,NaN,0,NaN,Scorpius,Sco,Scorpion
5593,KMT-2022-BLG-0440L b,Microlensing,KMTNet,2023,2023-05-26,15.40000,-7.40000,9.60000,0,Mass,...,NaN,0.373344,0,0,NaN,0,NaN,Sagittarius,Sgr,Archer
5598,OGLE-2019-BLG-1180L b,Microlensing,OGLE,2023,2024-01-05,555.24623,-161.13900,167.49557,0,Mass,...,NaN,0.377983,0,0,NaN,0,NaN,Sagittarius,Sgr,Archer

In [29]:
habitable = data["P_ESI"]>=0.5
data[habitable]

,P_NAME,P_HABITABLE,S_TYPE,S_TYPE_TEMP,S_TEMPERATURE,S_MASS,S_RADIUS,S_LOG_LUM,S_LOG_G,S_AGE,S_METALLICITY,S_DISTANCE,S_HZ_OPT_MIN,S_HZ_OPT_MAX,S_HZ_CON_MIN,S_HZ_CON_MAX,S_TIDAL_LOCK,S_SNOW_LINE,S_ABIO_ZONE,P_ESI
36,GJ 357 c,0,M2.5 V,M,3505.0,0.34,0.34,-1.798,4.94,NaN,-0.120,9.44181,0.103199,0.267735,0.130716,0.253832,0.321991,0.340693,0.028518,0.527043
113,TOI-904 c,2,NaN,M,3770.2,0.56,0.53,-1.292,4.62,1.50,0.022,46.08910,0.184076,0.471293,0.233160,0.446822,0.315478,0.610048,0.053116,0.658603
171,LP 791-18 c,0,M(6.1 +/- 0.7) V,M,2960.0,0.14,0.18,-2.638,5.12,0.50,-0.090,26.49270,0.039461,0.105069,0.049983,0.099612,0.165486,0.129528,0.008318,0.566472
210,L 98-59 d,0,M3 V,M,3412.0,0.31,0.31,-1.948,4.94,0.80,-0.500,10.61940,0.086927,0.226555,0.110106,0.214790,0.233271,0.286658,0.023570,0.527143
220,HD 219134 d,0,K3 V,K,4699.0,0.81,0.78,-0.577,4.57,11.00,0.110,6.53127,0.408480,1.000158,0.517403,0.948238,0.497300,1.389517,0.296245,0.509692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5529,Kepler-1126 b,0,NaN,G,5798.0,0.92,0.93,-0.099,4.46,5.50,-0.260,635.73600,0.668818,1.574883,0.847140,1.493132,0.462255,2.409150,2.042060,0.504522
5537,Kepler-1052 c,0,NaN,G,5818.0,0.94,0.85,-0.047,4.55,3.55,-0.220,943.44400,0.709225,1.669160,0.898320,1.582515,0.432818,2.557783,2.128650,0.598437
5555,Kepler-1126 c,0,NaN,G,5678.0,0.79,0.92,-0.099,4.41,0.30,-0.400,635.73600,0.673635,1.591423,0.853244,1.508814,0.270575,2.409150,1.579359,0.720645
5558,Kepler-311 d,0,NaN,G,5903.0,0.97,1.16,0.193,4.30,1.95,-0.100,778.65400,0.930136,2.184400,1.178129,2.071010,0.395811,3.371815,2.489272,0.577742
5581,Kepler-549 c,0,NaN,G,5360.0,0.88,0.84,-0.306,4.54,4.57,-0.030,635.14500,0.540562,1.289728,0.684696,1.222779,0.441610,1.898295,0.948056,0.539650